services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: nx run client:dev

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    command: nx run server:serve
