import { TaskType, TaskStatus } from './shared-types';

export const cardListData: TaskType[] = [
  {
    id: 1,
    title: 'Orange',
    description: 'Price: $5.50',
    status: TaskStatus.COMPLETED,
    priority: 1,
    created_at: '2021-10-10',
    updated_at: '2021-10-10',
    expired_at: '2021-10-10',
    willExpireInThreeDays: false,
    isExpired: false,
    subTasks: [],
    created_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
    updated_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
  },
  {
    id: 2,
    title: 'Tangerine',
    description: 'Price: $3.00',
    status: TaskStatus.PENDING,
    priority: 2,
    created_at: '2021-10-10',
    updated_at: '2021-10-10',
    expired_at: '2021-10-10',
    willExpireInThreeDays: false,
    isExpired: false,
    subTasks: [],
    created_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
    updated_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
  },
  {
    id: 3,
    title: 'Raspberry',
    description: 'Price: $10.00',
    status: TaskStatus.PENDING,
    priority: 3,
    created_at: '2021-10-10',
    updated_at: '2021-10-10',
    expired_at: '2021-10-10',
    willExpireInThreeDays: false,
    isExpired: false,
    subTasks: [],
    created_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
    updated_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
  },
  {
    id: 4,
    title: 'Lemon',
    description: 'Price: $5.30',
    status: TaskStatus.PENDING,
    priority: 4,
    created_at: '2021-10-10',
    updated_at: '2021-10-10',
    expired_at: '2021-10-10',
    willExpireInThreeDays: false,
    isExpired: false,
    subTasks: [],
    created_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
    updated_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
  },
  {
    id: 5,
    title: 'Avocado',
    description: 'Price: $15.70',
    status: TaskStatus.PENDING,
    priority: 5,
    created_at: '2021-10-10',
    updated_at: '2021-10-10',
    expired_at: '2021-10-10',
    willExpireInThreeDays: false,
    isExpired: false,
    subTasks: [],
    created_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
    updated_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
  },
  {
    id: 6,
    title: 'Lemon 2',
    description: 'Price: $8.00',
    status: TaskStatus.PROGRESS,
    priority: 6,
    created_at: '2021-10-10',
    updated_at: '2021-10-10',
    expired_at: '2021-10-10',
    willExpireInThreeDays: false,
    isExpired: false,
    subTasks: [],
    created_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
    updated_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
  },
  {
    id: 7,
    title: 'Banana',
    description: 'Price: $7.50',
    status: TaskStatus.PROGRESS,
    priority: 7,
    created_at: '2021-10-10',
    updated_at: '2021-10-10',
    expired_at: '2021-10-10',
    willExpireInThreeDays: false,
    isExpired: false,
    subTasks: [],
    created_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
    updated_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
  },
  {
    id: 8,
    title: 'Watermelon',
    description: 'Price: $12.20',
    status: TaskStatus.COMPLETED,
    priority: 8,
    created_at: '2021-10-10',
    updated_at: '2021-10-10',
    expired_at: '2021-10-10',
    willExpireInThreeDays: false,
    isExpired: false,
    subTasks: [],
    created_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
    updated_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
  },
  {
    id: 9,
    title: 'Pineapple',
    description: 'Price: $9.99',
    status: TaskStatus.PENDING,
    priority: 9,
    created_at: '2023-07-15',
    updated_at: '2023-07-15',
    expired_at: '2023-07-15',
    willExpireInThreeDays: false,
    isExpired: false,
    subTasks: [],
    created_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
    updated_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
  },
  {
    id: 10,
    title: 'Strawberry',
    description: 'Price: $15.00',
    status: TaskStatus.PROGRESS,
    priority: 10,
    created_at: '2023-07-15',
    updated_at: '2023-07-15',
    expired_at: '2023-07-15',
    willExpireInThreeDays: false,
    isExpired: false,
    subTasks: [],
    created_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
    updated_by: {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      avatar: 'https://example.com/avatar.jpg',
    },
  },
];
